# config.yaml
# List of source-destination pairs
mappings:
  - source: "/mnt/data-cache"
    # in case of unraid to move all to Array
    destination: "/mnt/user0"
    min_age: "35d"
    max_age: "1y"
    # qbit clients
    clients:
      - host: localhost:8080
        user: !ENV QBIT_USER
        password: !ENV QBIT_PASSWORD
  - source: "/mnt/app-cache"
    # ZFS dataset
    destination: "/mnt/rusty"
    min_age: "3d"
    include:
      - documents
ignore:
  - "**/.Orphaned"
  - "**/.RecycleBin"
  - "**/usenet/incomplete/**"
  - "**/torrents/**"
# find files but do not move
dry_run: true