# config.yaml
# List of source-destination pairs
mappings:
  # NOTE: disk usage for ZFS works on dataset level only
  # ZFS dataset -> Unraid Array folder
  - source: "/mnt/data-cache/data"
    # in case of unraid to move all to Array
    destination: "/mnt/user0/data"
    min_age: "35d"
    max_age: "1y"
    # keep mover running until threshold is reached.
    # It is going to prioritize files matching min_age -> with less links -> plex watched -> based on mtime
    # Careful with min_age usage as it will prevent files from being moved if file is younger than that, but disk usage is higher
    # Ideally min_age can be set to 1d, but files are gonna be sorted as explained above
    threshold: 70
    # move files back to cache if bellow this threshold, setting higher than threshold will help to rebalance based on plex state
    # Currently watching will be used as a source
    cache_threshold: 75
    # qbit clients
    clients:
      - host: localhost:8080
        user: !ENV QBIT_USER
        password: !ENV QBIT_PASSWORD
        # we need to be able to match host path with container path
        rewrite:
          # container mount point for qbit
          from: "/data"
          # host path on source
          to: "/mnt/data-cache/data"
    plex:
      - url: http://localhost:32400
        token: !ENV PLEX_TOKEN
        # we need to be able to match host path with container path
        rewrite:
          # container mount point for plex
          from: "/data"
          # host path on source
          to: "/mnt/data-cache/data"
        # Include only these libraries into plex checks, remove it to traverse all libraries
        libraries:
          - "TV Shows"
          - "Movies"
        # Include only these users into plex checks, remove it to traverse all users
        users:
          - "username_1"
          - "username_2"
    ignore:
      - "**/.Orphaned"
      - "**/.RecycleBin"
      - "**/usenet/incomplete/**"
      - "**/torrents/**"
  # ZFS dataset -> ZFS dataset
  - source: "/mnt/app-cache/documents"
    destination: "/mnt/rusty/documents"
    min_age: "3d"
  # XFS cache -> Unraid Array 
  - source: "/mnt/other-cache/share1"
    destination: "/mnt/user0/share1"
    min_age: "3d"